Spring Boot intro 1.0
aksoli666/shop pull request #1
Opened 2024-10-02 12:38 UTC by aksoli666

added checkstyle and the following property;
created a .github directory with workflows and ci.yml; created Book entity;
created BookRepository and BookRepositoryImpl;
created BookService and BookServiceImpl;
added CommandLineRunner bean to main class;

2024-10-02 12:47 UTC, Elena-Bruyako requested changes
see comments

2024-10-02 12:47 UTC, Elena-Bruyako commented on src/main/java/shop/config/AppConfig.java
> +public class AppConfig {
remove class

2024-10-02 12:47 UTC, Elena-Bruyako commented on src/main/java/shop/entity/Book.java
> +@Data
```suggestion
@Getter
@Setter
```

2024-10-02 12:47 UTC, Elena-Bruyako commented on src/main/java/shop/repository/impl/BookRepositoryImpl.java
> +@Repository
```suggestion
@Repository
@RequiredArgsConstructor
```

2024-10-02 12:47 UTC, Elena-Bruyako commented on src/main/java/shop/repository/impl/BookRepositoryImpl.java
> +    }
```suggestion
```

2024-10-02 12:47 UTC, Elena-Bruyako commented on src/main/java/shop/repository/impl/BookRepositoryImpl.java
> +            throw new EntityExistsException("Book already exists or something is wrong. "
```suggestion
            throw new DataProcessingException("Can't save book: " + book, e");
```

2024-10-02 12:47 UTC, Elena-Bruyako commented on src/main/java/shop/repository/impl/BookRepositoryImpl.java
> +            throw new RuntimeException("Error finding all books", e);
```suggestion
            throw new DataProcessingException("Fetching books failed", e);
```

2024-10-02 12:47 UTC, Elena-Bruyako commented on src/main/java/shop/repository/impl/BookRepositoryImpl.java
> +            return session.createQuery("SELECT b FROM Book b", Book.class).getResultList();
```suggestion
            return session.createQuery("FROM Book", Book.class).getResultList();
```

2024-10-02 12:47 UTC, Elena-Bruyako commented on src/main/java/shop/service/impl/BookServiceImpl.java
> +@Service
```suggestion
@Service
@RequiredArgsConstructor
```

2024-10-02 12:47 UTC, Elena-Bruyako commented on src/main/java/shop/service/impl/BookServiceImpl.java
> +    }
```suggestion
```

2024-10-03 08:28 UTC, okuzan approved these changes

2024-10-06 18:55 UTC, merged