Test 1.0
aksoli666/shop pull request #14
Opened 2024-11-11 20:58 UTC by aksoli666

![controller-test-coverage](https://github.com/user-attachments/assets/ab0a2f35-5bd8-467a-b5db-71b1d89a97ed)
![service-test-coverage](https://github.com/user-attachments/assets/723bee1a-cc6d-4968-8d69-08fde19e838a)
added tests for Book repository and tests for service, controller layers for Book and Category

2024-11-12 11:11 UTC, Elena-Bruyako requested changes

2024-11-12 11:11 UTC, Elena-Bruyako commented on src/test/java/shop/controller/CategoryControllerTest.java
> +    private static final String ADD_CATEGORIES_SQL =
it's better to remove these constants and use `@Sql` under the test class with all scripts that you need

2024-11-12 11:11 UTC, Elena-Bruyako commented on src/test/java/shop/service/BookServiceTest.java
> +        book.setId(ID_1L_CORRECT);
check if you have duplication and use separate methods for creating test data 
Also, you can create TestUtil class with methods that return test data and TestConstants for constants

2024-11-12 11:11 UTC, Elena-Bruyako commented on src/test/resources/changelog/db.changelog-master.yaml
> +databaseChangeLog:
redundant

2024-11-12 11:11 UTC, Elena-Bruyako commented on src/test/resources/database/shop/category/delete-categories.sql
> +DELETE FROM categories WHERE id IN (6, 7);
why do you need so many delete scripts?

2024-11-12 11:11 UTC, Elena-Bruyako commented on src/test/resources/database/shop/category/add-category-for-delete-by-id.sql
> +INSERT INTO categories (id, name, description, is_deleted) VALUES (10, "Y Category", "Y Description for Category Y", 0)
why do you need so many insert scripts?

2024-11-13 12:39 UTC, okuzan approved these changes

2024-11-13 17:10 UTC, merged