Security 1.0
aksoli666/shop pull request #7
Opened 2024-10-20 13:09 UTC by aksoli666

added User entity and required dto`s
added method register and have repo, service, controller layers used data validation
added @FieldMatcher
added RegistrationException

2024-10-20 18:10 UTC, Elena-Bruyako requested changes
see comments

2024-10-20 18:10 UTC, Elena-Bruyako commented on src/main/java/shop/annatation/FieldMatch.java
> +package shop.annatation;
```suggestion
package shop.validation;
```

2024-10-20 18:10 UTC, Elena-Bruyako commented on src/main/java/shop/validator/FieldMatchValidator.java
> +package shop.validator;
```suggestion
package shop.validation;
```

2024-10-20 18:10 UTC, Elena-Bruyako commented on src/main/java/shop/validator/FieldMatchValidator.java
> +        if (firstFieldValue != null && secondFieldValue != null) {
You can use Objects.equals here

2024-10-20 18:10 UTC, Elena-Bruyako commented on src/main/java/shop/dto/request/RegisterUserRequestDto.java
> +public class RegisterUserRequestDto {
```suggestion
public class UserRegistrationRequestDto {
```

2024-10-20 18:10 UTC, Elena-Bruyako commented on src/main/java/shop/dto/responce/RegisterUserResponseDto.java
> +public class RegisterUserResponseDto {
```suggestion
public class UserResponseDto {
```

2024-10-20 18:10 UTC, Elena-Bruyako commented on src/main/java/shop/dto/responce/RegisterUserResponseDto.java
> +    @NotBlank
don't need validate response

2024-10-20 18:10 UTC, Elena-Bruyako commented on src/main/java/shop/entity/User.java
> +    )
```suggestion
    @Column(nullable = false)
```

2024-10-20 18:10 UTC, Elena-Bruyako commented on src/main/java/shop/entity/User.java
> +    )
```suggestion
    @Column(nullable = false)
```

2024-10-20 18:10 UTC, Elena-Bruyako commented on src/main/java/shop/entity/User.java
> +    @Column(name = "shipping_address")
```suggestion
```

2024-10-20 18:10 UTC, Elena-Bruyako commented on src/main/java/shop/entity/User.java
> +    )
```suggestion
    @Column(unique = true, nullable = false)
```

2024-10-20 18:10 UTC, Elena-Bruyako commented on src/main/java/shop/service/impl/UserServiceImpl.java
> +        if (userRepository.findByEmail(registerUserRequestDto.getEmail()).isPresent()) {
```suggestion
        if (userRepository.existsByEmail(registerUserRequestDto.getEmail())) {
```

2024-10-20 18:10 UTC, Elena-Bruyako commented on src/main/java/shop/service/impl/UserServiceImpl.java
> +        return userMapper.toRegisterUserResponseDto(savedUser);
```suggestion
        userRepository.save(user);
        return userMapper.toRegisterUserResponseDto(user);
```

2024-10-20 18:10 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/02.-create-users-table.yaml
> +                  type: varchar(255)
did you add 02 changelog to master changelog? 

Add empty line at the end of file

2024-10-21 11:00 UTC, ahoienko approved these changes
Good job!

2024-10-21 14:32 UTC, merged