Spring Boot Security 1.0
aksoli666/shop pull request #8
Opened 2024-10-21 21:53 UTC by aksoli666

added spring-boot-starter-security
added SecurityConfig
created CustomUserDetailsService
implemented UserDetails in the User
/auth/** -> public, other -> accessible before auth added role entity and repo layer
added all liquibase changesets
used @PreAuthorisation

2024-10-21 23:12 UTC, aksoli666 commented
Hi, I have a problem sending requests to create a book from a user with the role of user, the request is successful, but it should not work like this. How do I properly fix the code because I can't find the error?

2024-10-22 07:19 UTC, liliia-ponomarenko requested changes
Good job! Let’s fix a few mistakes ;)

2024-10-22 07:19 UTC, liliia-ponomarenko commented on src/main/java/shop/dto/request/UserRegistrationRequestDto.java
> +    private Set<Role> roles;
NotEmpty

2024-10-22 07:19 UTC, liliia-ponomarenko commented on src/main/java/shop/entity/User.java
> +    @ManyToMany(fetch = FetchType.EAGER)
Don't use EAGER fetch type

2024-10-22 07:19 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
> +                  type: bit
```suggestion
                  type: tinyint(1)
```

2024-10-22 07:19 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/04-create-users-table.yaml
> +
This is normal at the training stage, but you should understand that on real projects you will never change existing files, but always create a new one for new changes

2024-10-22 17:36 UTC, Elena-Bruyako requested changes
see comments

2024-10-22 17:36 UTC, Elena-Bruyako commented on src/main/java/shop/config/SecurityConfig.java
> +@EnableMethodSecurity
leave only one annotation

2024-10-22 17:36 UTC, Elena-Bruyako commented on src/main/java/shop/dto/request/CreateBookRequestDto.java
> +
remove empty line

2024-10-22 17:36 UTC, Elena-Bruyako commented on src/main/java/shop/dto/request/UserRegistrationRequestDto.java
> +    private Set<Role> roles;
don't need to provide roles in UserRegistrationRequestDto
```suggestion
```

2024-10-22 17:36 UTC, Elena-Bruyako commented on src/main/java/shop/dto/responce/UserResponseDto.java
> +    private Set<Role> roles;
```suggestion
```

2024-10-22 17:36 UTC, Elena-Bruyako commented on src/main/java/shop/entity/User.java
> +    @ManyToMany()
```suggestion
    @ManyToMany
```

2024-10-22 17:36 UTC, Elena-Bruyako commented on src/main/java/shop/entity/User.java
> +                .collect(Collectors.toSet());
```suggestion
        return roles;
```

2024-10-22 17:36 UTC, Elena-Bruyako commented on src/main/java/shop/mapper/UserMapper.java
> +    @Mapping(target = "roles", source = "roles")
```suggestion
```

2024-10-22 17:36 UTC, Elena-Bruyako commented on src/main/java/shop/service/impl/UserServiceImpl.java
> +        user.setPassword(passwordEncoder.encode(registerUserRequestDto.getPassword()));
set ROLE USER
```suggestion
        user.setPassword(passwordEncoder.encode(registerUserRequestDto.getPassword()));
        user.setRole(Set.of(....
```

2024-10-23 08:24 UTC, ahoienko requested changes
very good, left minor comment

2024-10-23 08:24 UTC, ahoienko commented on src/main/java/shop/repository/role/RoleRepository.java
> +    Role findByRole(Role.RoleName role);
```suggestion
    Optional<Role> findByRole(Role.RoleName role);
```

2024-10-23 09:34 UTC, JJJazl approved these changes

2024-10-23 09:34 UTC, JJJazl commented on src/main/java/shop/repository/role/RoleRepository.java
> +    Optional<Role> findByRole(Role.RoleName role);
```suggestion
    Optional<Role> findByRoleName(Role.RoleName roleName);
```

2024-10-23 09:34 UTC, JJJazl commented on src/main/java/shop/service/impl/UserServiceImpl.java
> +                .orElseThrow(() -> new EntityNotFoundException("Can`t find role"))));
Let's make the code more explicit and the exception messages more informative
```suggestion
RoleName userRoleName = Role.RoleName.ROLE_USER
        user.setRoles(Set.of(roleRepository.findByRoleName(userRoleName)
                .orElseThrow(() -> new EntityNotFoundException("Can`t find role: " + userRoleName.name()))));
```

2024-10-23 12:01 UTC, merged